"""YAML への書き出しと drift 検出ヘルパ。

決定論的な YAML を出すことが最優先。並び順は :mod:`thor.manifest.introspect`
が組み立てた dict の順序をそのまま採用し、``yaml.safe_dump`` の
``sort_keys=False`` で保持する。
"""
from __future__ import annotations

import difflib
from pathlib import Path
from typing import Any, Iterable

import yaml

# 生成物 3 種のファイル名
TOOLS_FILE = "tools.yaml"
AGENTS_FILE = "agents.yaml"
CREWS_FILE = "crews.yaml"

_HEADER = (
    "# AUTO-GENERATED by thor.manifest -- DO NOT EDIT BY HAND.\n"
    "# Regenerate with:  python -m thor.manifest --out agent_studio_manifest/\n"
    "# CI drift check :  python -m thor.manifest --check --out agent_studio_manifest/\n"
    "# Source of truth : Python code under thor.tools / thor.<crew>.crew\n"
)


def dump_manifest_yaml(manifest: dict[str, Any]) -> str:
    """dict を決定論的な YAML 文字列に変換する (先頭にヘッダコメント付き)。"""
    body = yaml.safe_dump(
        manifest,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=120,
    )
    return _HEADER + body


def write_manifest_file(path: Path, manifest: dict[str, Any]) -> None:
    """dict を YAML として path に書き出す (親ディレクトリは自動作成)。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    text = dump_manifest_yaml(manifest)
    path.write_text(text, encoding="utf-8")


def write_manifests(
    out_dir: Path,
    tools: dict[str, Any],
    agents: dict[str, Any],
    crews: dict[str, Any],
) -> list[Path]:
    """3 マニフェストを out_dir に書き出し、書いたパスのリストを返す。"""
    out_dir.mkdir(parents=True, exist_ok=True)
    files = [
        (out_dir / TOOLS_FILE, tools),
        (out_dir / AGENTS_FILE, agents),
        (out_dir / CREWS_FILE, crews),
    ]
    for path, manifest in files:
        write_manifest_file(path, manifest)
    return [p for p, _ in files]


def diff_manifest(path: Path, expected: dict[str, Any]) -> str:
    """path 上の既存ファイルと ``expected`` を dump した文字列を比較する。

    差分がなければ空文字。あれば unified diff を返す。ファイル未存在なら全体を diff。
    """
    expected_text = dump_manifest_yaml(expected)
    actual_text = path.read_text(encoding="utf-8") if path.exists() else ""
    if expected_text == actual_text:
        return ""
    diff_lines: Iterable[str] = difflib.unified_diff(
        actual_text.splitlines(keepends=True),
        expected_text.splitlines(keepends=True),
        fromfile=f"{path} (on disk)",
        tofile=f"{path} (regenerated)",
    )
    return "".join(diff_lines)


__all__ = [
    "TOOLS_FILE",
    "AGENTS_FILE",
    "CREWS_FILE",
    "dump_manifest_yaml",
    "write_manifest_file",
    "write_manifests",
    "diff_manifest",
]
